# -*- coding: utf-8 -*-
"""Project_1_HousePrizePrediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13CgdMllUZobtluiN0cnhXEiW3hfEM3ta
"""

!mkdir ~/.kaggle
!cd kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
!kaggle datasets download -d camnugent/california-housing-prices

!unzip california-housing-prices.zip

import pandas as pd

housing_pd = pd.read_csv('housing.csv')
housing_pd.head()

housing_pd['ocean_proximity'].value_counts()

housing_pd_shuffled = housing_pd.sample(n=len(housing_pd), random_state=1)
housing_pd_shuffled

pd.get_dummies(housing_pd_shuffled['ocean_proximity'], dtype=int).head()

housing_pd_shuffled.drop('ocean_proximity', axis=1).head()

housing_pd_final = pd.concat([housing_pd_shuffled.drop('ocean_proximity', axis=1),pd.get_dummies(housing_pd_shuffled['ocean_proximity'], dtype=int)], axis=1)

housing_pd_final

housing_pd_final = housing_pd_final[['longitude',	'latitude',	'housing_median_age',
                                     'total_rooms',	'total_bedrooms',	'population',
                                     'households',	'median_income','<1H OCEAN',	'INLAND',
                                     'ISLAND',	'NEAR BAY',	'NEAR OCEAN',
                                     'median_house_value']]

housing_pd_final

housing_pd_final = housing_pd_final.dropna()
len(housing_pd_final)

train_pd, test_pd, val_pd = housing_pd_final[:18000], housing_pd_final[18000:19217], housing_pd_final[19215:]
len(train_pd), len(test_pd), len(val_pd)

X_train, y_train = train_pd.to_numpy()[:, :-1], train_pd.to_numpy()[:, -1]
X_val, y_val = val_pd.to_numpy()[:, :-1], val_pd.to_numpy()[:, -1]
X_test, y_test = test_pd.to_numpy()[:, :-1], test_pd.to_numpy()[:, -1]

X_train.shape, y_train.shape, X_val.shape, y_val.shape, X_test.shape, y_test.shape

from sklearn.preprocessing import StandardScaler
import numpy as np

scaler = StandardScaler().fit(X_train[:, :8])

def preprocessor(X):
  A = np.copy(X)
  A[:, :8] = scaler.transform(A[:, :8])
  return A

X_train, X_val, X_text = preprocessor(X_train), preprocessor(X_val), preprocessor(X_test)
X_train

X_train.shape, y_train.shape, X_val.shape, y_val.shape, X_test.shape, y_test.shape

pd.DataFrame(X_train).head()

pd.DataFrame(X_train).hist(figsize = (15, 8))

from sklearn.metrics import mean_squared_error as mse
from sklearn.linear_model import LinearRegression

lm = LinearRegression().fit(X_train, y_train)
mse(lm.predict(X_train), y_train, squared = False), mse(lm.predict(X_val), y_val, squared = False)

from sklearn.neighbors import KNeighborsRegressor

knn = KNeighborsRegressor(n_neighbors = 10).fit(X_train, y_train)
mse(knn.predict(X_train), y_train, squared = False), mse(knn.predict(X_val), y_val, squared = False)

from sklearn.ensemble import RandomForestRegressor

rfr = RandomForestRegressor(max_depth=8).fit(X_train, y_train)
mse(rfr.predict(X_train), y_train, squared=False), mse(knn.predict(X_val), y_val, squared=False)

from sklearn.ensemble import GradientBoostingRegressor

gbr = GradientBoostingRegressor(n_estimators=10).fit(X_train, y_train)
mse(gbr.predict(X_train), y_train, squared = False), mse(gbr.predict(X_val), y_val, squared = False)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.metrics import RootMeanSquaredError
from tensorflow.keras.optimizers import Adam

simple_nn = Sequential()
simple_nn.add(InputLayer((13,)))
simple_nn.add(Dense(2, 'relu'))
simple_nn.add(Dense(1, 'linear'))

opt = Adam(learning_rate=.1)
cp = ModelCheckpoint('models/simple_nn', save_best_only = True)
simple_nn.compile(optimizer=opt, loss='mse', metrics=[RootMeanSquaredError()])
simple_nn.fit(x=X_train, y=y_train, validation_data=(X_val, y_val), epochs=100, callbacks=[cp])

from tensorflow.keras.models import load_model

simple_nn = load_model('models/simple_nn')
mse(simple_nn.predict(X_train), y_train, squared = False), mse(simple_nn.predict(X_val), y_val, squared = False)

Medium_nn = Sequential()
Medium_nn.add(InputLayer((13,)))
Medium_nn.add(Dense(2, 'relu'))
Medium_nn.add(Dense(1, 'linear'))

opt = Adam(learning_rate=.1)
cp = ModelCheckpoint('models/Medium_nn', save_best_only = True)
Medium_nn.compile(optimizer=opt, loss='mse', metrics=[RootMeanSquaredError()])
Medium_nn.fit(x=X_train, y=y_train, validation_data=(X_val, y_val), epochs=100, callbacks=[cp])

Medium_nn = load_model('models/Medium_nn')
mse(Medium_nn.predict(X_train), y_train, squared = False), mse(Medium_nn.predict(X_val), y_val, squared = False)

large_nn = Sequential()
large_nn.add(InputLayer((13,)))
large_nn.add(Dense(256, 'relu'))
large_nn.add(Dense(128, 'relu'))
large_nn.add(Dense(64, 'relu'))
large_nn.add(Dense(32, 'relu'))
large_nn.add(Dense(1, 'linear'))

opt = Adam(learning_rate=.1)
cp = ModelCheckpoint('models/large_nn', save_best_only = True)
large_nn.compile(optimizer=opt, loss='mse', metrics=[RootMeanSquaredError()])
large_nn.fit(x=X_train, y=y_train, validation_data=(X_val, y_val), epochs=100, callbacks=[cp])

large_nn = load_model('models/large_nn')
mse(large_nn.predict(X_train), y_train, squared = False), mse(large_nn.predict(X_val), y_val, squared = False)

mse(gbr.predict(X_test), y_test, squared = False)